### ISSUE TITLE
Notifications on new posts

### ISSUE THREAD

**Issue by lsolesen** [jdvp/jekyll-comments-google-forms#4]
How do you get notified about new posts, so you can easily answer them?

**Comment by jdvp** [comment]
If you set up the google form with a secondary user account and then give access to your primary, you can set up notifications in the regular way (using notification settings). This doesn't work if using a single user though afaik 

| Google Sheets Notification Settings |
|-----|
| <img width="687" alt="Screenshot 2022-11-11 at 11 03 27 PM" src="https://user-images.githubusercontent.com/7111196/201461989-d1638a9d-2a60-49a6-8d75-c72e1e476fcf.png"> |

What I've personally been doing is using IFTTT to be notified:
| IFTTT |
|-----|
| <img width="724" alt="Screenshot 2022-11-11 at 11 06 21 PM" src="https://user-images.githubusercontent.com/7111196/201462063-33e2fd28-d2ae-431b-ba6b-ea9ecb747a1f.png"> |

**Comment by jdvp** [comment]
Closing
