### ISSUE TITLE
Google crawling or indexing comments?

### ISSUE THREAD

**Issue by blazer2k1** [jdvp/jekyll-comments-google-forms#7]
So far I don't see it on your site with lazy loading which is good since it will discourage most spammers.

**Comment by jdvp** [comment]
Sorry I am unfamiliar with all the google crawling stuff? Do you have any more details?

My site does have a robots.txt that should allow google to crawl the site but and I don't think I added anything to specific to prevent google from crawling the specific comment section but IDR

recaptcha has been working well for spammers for me personally I think though

**Comment by blazer2k1** [comment]
I think if the comments are not lazy loaded and chunked it should get google to crawl most of it.
